


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."is_family_member"("_family_id" "uuid") RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select exists (
    select 1
    from public.family_members fm
    where fm.family_id = _family_id
      and fm.user_email = auth.email()
  );
$$;


ALTER FUNCTION "public"."is_family_member"("_family_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_family_principal"("_family_id" "uuid") RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select exists (
    select 1
    from public.families f
    where f.id = _family_id
      and f.principal_email = auth.email()
  );
$$;


ALTER FUNCTION "public"."is_family_principal"("_family_id" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."administration_records" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "patient_id" bigint,
    "medication_id" "uuid",
    "medication_name" "text",
    "medication_dosage" "text",
    "scheduled_dose_id" "uuid",
    "scheduled_datetime" timestamp with time zone,
    "actual_datetime" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "text" DEFAULT 'on_time'::"text" NOT NULL,
    "delay_minutes" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_system_generated" boolean DEFAULT false NOT NULL,
    "recorded_by_name" "text",
    "recorded_by_email" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "administration_records_status_check" CHECK (("status" = ANY (ARRAY['on_time'::"text", 'delayed'::"text", 'missed'::"text", 'incorrect'::"text"])))
);


ALTER TABLE "public"."administration_records" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."appointments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "family_id" "uuid",
    "patient_id" bigint,
    "datetime" timestamp with time zone,
    "specialty" "text",
    "location" "text",
    "notes" "text"
);


ALTER TABLE "public"."appointments" OWNER TO "postgres";


ALTER TABLE "public"."appointments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."appointments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."care_records" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "patient_id" bigint,
    "record_type" "text" NOT NULL,
    "actual_time" timestamp with time zone DEFAULT "now"() NOT NULL,
    "recorded_by_name" "text",
    "recorded_by_email" "text",
    "is_system" boolean DEFAULT false NOT NULL,
    "notes" "text",
    "details" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."care_records" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."families" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "patient_name" "text",
    "pin" "text" NOT NULL,
    "principal_email" "text" NOT NULL,
    "principal_name" "text",
    "patient_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "families_pin_check" CHECK (("pin" ~ '^[0-9]{4}$'::"text"))
);


ALTER TABLE "public"."families" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."family_members" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "user_email" "text" NOT NULL,
    "user_name" "text",
    "role" "text" NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true NOT NULL,
    CONSTRAINT "family_members_role_check" CHECK (("role" = ANY (ARRAY['principal'::"text", 'member'::"text"])))
);


ALTER TABLE "public"."family_members" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."medication_changes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "patient_id" bigint,
    "medication_id" "uuid",
    "medication_name" "text" NOT NULL,
    "suggested_by_name" "text",
    "suggested_by_email" "text",
    "reason" "text",
    "professional_confirmation" boolean DEFAULT false NOT NULL,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "reviewed_by_name" "text",
    "reviewed_by_email" "text",
    "reviewed_at" timestamp with time zone,
    CONSTRAINT "medication_changes_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."medication_changes" OWNER TO "postgres";


ALTER TABLE "public"."medication_changes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."medication_changes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."medications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "patient_id" bigint,
    "name" "text" NOT NULL,
    "dosage" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text" DEFAULT 'fixed'::"text",
    "fixed_times" "text"[] DEFAULT '{}'::"text"[],
    "interval_hours" integer,
    "duration_type" "text" DEFAULT 'continuous'::"text",
    "duration_days" integer,
    "start_date" "date",
    "end_date" "date",
    "instructions" "text"
);


ALTER TABLE "public"."medications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."next_doses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "family_id" "uuid" NOT NULL,
    "patient_id" bigint,
    "medication_id" "uuid",
    "status" "text" DEFAULT 'pendente'::"text" NOT NULL,
    "due_datetime" timestamp with time zone,
    "is_first_dose" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "medication_name" "text",
    "due_at" timestamp with time zone,
    CONSTRAINT "next_doses_status_check" CHECK (("status" = ANY (ARRAY['pendente'::"text", 'concluida'::"text"])))
);


ALTER TABLE "public"."next_doses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."patients" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "family_id" "uuid",
    "name" "text",
    "birthdate" "date",
    "notes" "text",
    "photo_url" "text"
);


ALTER TABLE "public"."patients" OWNER TO "postgres";


ALTER TABLE "public"."patients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."patients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."administration_records"
    ADD CONSTRAINT "administration_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."appointments"
    ADD CONSTRAINT "appointments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."care_records"
    ADD CONSTRAINT "care_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "families_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."family_members"
    ADD CONSTRAINT "family_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."medication_changes"
    ADD CONSTRAINT "medication_changes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."medications"
    ADD CONSTRAINT "medications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."next_doses"
    ADD CONSTRAINT "next_doses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."patients"
    ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_admin_records_actual_dt" ON "public"."administration_records" USING "btree" ("actual_datetime");



CREATE INDEX "idx_admin_records_family" ON "public"."administration_records" USING "btree" ("family_id");



CREATE INDEX "idx_families_principal_email" ON "public"."families" USING "btree" ("principal_email");



CREATE INDEX "idx_family_members_email" ON "public"."family_members" USING "btree" ("user_email");



CREATE INDEX "idx_family_members_family" ON "public"."family_members" USING "btree" ("family_id");



CREATE INDEX "idx_medications_family" ON "public"."medications" USING "btree" ("family_id");



CREATE INDEX "idx_medications_patient" ON "public"."medications" USING "btree" ("patient_id");



CREATE INDEX "idx_next_doses_family" ON "public"."next_doses" USING "btree" ("family_id");



CREATE INDEX "idx_next_doses_status" ON "public"."next_doses" USING "btree" ("status");



CREATE INDEX "idx_patients_family" ON "public"."patients" USING "btree" ("family_id");



CREATE INDEX "medication_changes_family_id_idx" ON "public"."medication_changes" USING "btree" ("family_id");



CREATE INDEX "medication_changes_family_status_idx" ON "public"."medication_changes" USING "btree" ("family_id", "status");



CREATE INDEX "medication_changes_status_idx" ON "public"."medication_changes" USING "btree" ("status");



ALTER TABLE ONLY "public"."administration_records"
    ADD CONSTRAINT "administration_records_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."administration_records"
    ADD CONSTRAINT "administration_records_medication_id_fkey" FOREIGN KEY ("medication_id") REFERENCES "public"."medications"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."administration_records"
    ADD CONSTRAINT "administration_records_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."appointments"
    ADD CONSTRAINT "appointments_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."appointments"
    ADD CONSTRAINT "appointments_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."care_records"
    ADD CONSTRAINT "care_records_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."care_records"
    ADD CONSTRAINT "care_records_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."family_members"
    ADD CONSTRAINT "family_members_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."medication_changes"
    ADD CONSTRAINT "medication_changes_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."medication_changes"
    ADD CONSTRAINT "medication_changes_medication_id_fkey" FOREIGN KEY ("medication_id") REFERENCES "public"."medications"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."medication_changes"
    ADD CONSTRAINT "medication_changes_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."medications"
    ADD CONSTRAINT "medications_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."medications"
    ADD CONSTRAINT "medications_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."next_doses"
    ADD CONSTRAINT "next_doses_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."next_doses"
    ADD CONSTRAINT "next_doses_medication_id_fkey" FOREIGN KEY ("medication_id") REFERENCES "public"."medications"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."next_doses"
    ADD CONSTRAINT "next_doses_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."patients"
    ADD CONSTRAINT "patients_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE CASCADE;



ALTER TABLE "public"."administration_records" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "administration_records_delete" ON "public"."administration_records" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "administration_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "administration_records_insert" ON "public"."administration_records" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "administration_records"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "administration_records_select" ON "public"."administration_records" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "administration_records"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "administration_records_update" ON "public"."administration_records" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "administration_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "administration_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



ALTER TABLE "public"."appointments" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "appointments_delete" ON "public"."appointments" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "appointments"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "appointments_insert" ON "public"."appointments" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "appointments"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "appointments_select" ON "public"."appointments" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "appointments"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "appointments_update" ON "public"."appointments" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "appointments"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "appointments"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



ALTER TABLE "public"."care_records" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "care_records_delete" ON "public"."care_records" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "care_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "care_records_insert" ON "public"."care_records" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "care_records"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "care_records_select" ON "public"."care_records" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "care_records"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "care_records_update" ON "public"."care_records" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "care_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "care_records"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



ALTER TABLE "public"."families" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "families_delete" ON "public"."families" FOR DELETE TO "authenticated" USING ("public"."is_family_principal"("id"));



CREATE POLICY "families_insert" ON "public"."families" FOR INSERT TO "authenticated" WITH CHECK (("principal_email" = "auth"."email"()));



CREATE POLICY "families_select" ON "public"."families" FOR SELECT TO "authenticated" USING (("public"."is_family_member"("id") OR ("principal_email" = "auth"."email"())));



CREATE POLICY "families_update" ON "public"."families" FOR UPDATE TO "authenticated" USING ("public"."is_family_principal"("id")) WITH CHECK ("public"."is_family_principal"("id"));



ALTER TABLE "public"."family_members" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "family_members_delete" ON "public"."family_members" FOR DELETE TO "authenticated" USING ("public"."is_family_principal"("family_id"));



CREATE POLICY "family_members_insert" ON "public"."family_members" FOR INSERT TO "authenticated" WITH CHECK (("public"."is_family_principal"("family_id") OR ("user_email" = "auth"."email"())));



CREATE POLICY "family_members_select" ON "public"."family_members" FOR SELECT TO "authenticated" USING (("public"."is_family_member"("family_id") OR "public"."is_family_principal"("family_id")));



CREATE POLICY "family_members_update" ON "public"."family_members" FOR UPDATE TO "authenticated" USING ("public"."is_family_principal"("family_id")) WITH CHECK ("public"."is_family_principal"("family_id"));



ALTER TABLE "public"."medication_changes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "medication_changes_delete" ON "public"."medication_changes" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "medication_changes_delete_family_members" ON "public"."medication_changes" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medication_changes_insert" ON "public"."medication_changes" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medication_changes_insert_family_members" ON "public"."medication_changes" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medication_changes_select" ON "public"."medication_changes" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medication_changes_select_family_members" ON "public"."medication_changes" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medication_changes_update" ON "public"."medication_changes" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "medication_changes_update_family_members" ON "public"."medication_changes" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medication_changes"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



ALTER TABLE "public"."medications" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "medications_delete" ON "public"."medications" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medications"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "medications_insert" ON "public"."medications" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medications"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medications_select" ON "public"."medications" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medications"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "medications_update" ON "public"."medications" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medications"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "medications"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



ALTER TABLE "public"."next_doses" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "next_doses_delete" ON "public"."next_doses" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "next_doses"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "next_doses_insert" ON "public"."next_doses" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "next_doses"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "next_doses_select" ON "public"."next_doses" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "next_doses"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "next_doses_update" ON "public"."next_doses" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "next_doses"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "next_doses"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



ALTER TABLE "public"."patients" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "patients_delete" ON "public"."patients" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "patients"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));



CREATE POLICY "patients_insert" ON "public"."patients" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "patients"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "patients_select" ON "public"."patients" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "patients"."family_id") AND ("fm"."user_email" = "auth"."email"())))));



CREATE POLICY "patients_update" ON "public"."patients" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "patients"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."family_members" "fm"
  WHERE (("fm"."family_id" = "patients"."family_id") AND ("fm"."user_email" = "auth"."email"()) AND ("fm"."role" = 'principal'::"text")))));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."is_family_member"("_family_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_family_member"("_family_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_family_member"("_family_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."is_family_principal"("_family_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_family_principal"("_family_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_family_principal"("_family_id" "uuid") TO "service_role";


















GRANT ALL ON TABLE "public"."administration_records" TO "anon";
GRANT ALL ON TABLE "public"."administration_records" TO "authenticated";
GRANT ALL ON TABLE "public"."administration_records" TO "service_role";



GRANT ALL ON TABLE "public"."appointments" TO "anon";
GRANT ALL ON TABLE "public"."appointments" TO "authenticated";
GRANT ALL ON TABLE "public"."appointments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."appointments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."appointments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."appointments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."care_records" TO "anon";
GRANT ALL ON TABLE "public"."care_records" TO "authenticated";
GRANT ALL ON TABLE "public"."care_records" TO "service_role";



GRANT ALL ON TABLE "public"."families" TO "anon";
GRANT ALL ON TABLE "public"."families" TO "authenticated";
GRANT ALL ON TABLE "public"."families" TO "service_role";



GRANT ALL ON TABLE "public"."family_members" TO "anon";
GRANT ALL ON TABLE "public"."family_members" TO "authenticated";
GRANT ALL ON TABLE "public"."family_members" TO "service_role";



GRANT ALL ON TABLE "public"."medication_changes" TO "anon";
GRANT ALL ON TABLE "public"."medication_changes" TO "authenticated";
GRANT ALL ON TABLE "public"."medication_changes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."medication_changes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."medication_changes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."medication_changes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."medications" TO "anon";
GRANT ALL ON TABLE "public"."medications" TO "authenticated";
GRANT ALL ON TABLE "public"."medications" TO "service_role";



GRANT ALL ON TABLE "public"."next_doses" TO "anon";
GRANT ALL ON TABLE "public"."next_doses" TO "authenticated";
GRANT ALL ON TABLE "public"."next_doses" TO "service_role";



GRANT ALL ON TABLE "public"."patients" TO "anon";
GRANT ALL ON TABLE "public"."patients" TO "authenticated";
GRANT ALL ON TABLE "public"."patients" TO "service_role";



GRANT ALL ON SEQUENCE "public"."patients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."patients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."patients_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


